-- CreateTable
CREATE TABLE `RecurringTransaction` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(180) NOT NULL,
    `valor` DECIMAL(12, 2) NOT NULL,
    `tipo` ENUM('receita', 'despesa') NOT NULL,
    `status` ENUM('confirmado', 'pendente') NOT NULL DEFAULT 'confirmado',
    `categoria` VARCHAR(80) NOT NULL,
    `observacao` VARCHAR(500),
    `accountId` INTEGER NOT NULL,
    `categoryId` INTEGER,
    `userId` INTEGER NOT NULL,
    `frequency` ENUM('daily', 'weekly', 'monthly', 'yearly') NOT NULL,
    `interval` INTEGER NOT NULL DEFAULT 1,
    `startDate` DATE NOT NULL,
    `endDate` DATE,
    `nextRun` DATE,
    `lastRun` DATETIME(3),
    `maxExecutions` INTEGER,
    `executedCount` INTEGER NOT NULL DEFAULT 0,
    `autoAdjustDay` BOOLEAN NOT NULL DEFAULT true,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX `RecurringTransaction_userId_isActive_idx`(`userId`, `isActive`),
    INDEX `RecurringTransaction_accountId_idx`(`accountId`),
    INDEX `RecurringTransaction_nextRun_idx`(`nextRun`),
    PRIMARY KEY (`id`),
    CONSTRAINT `RecurringTransaction_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `Account`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `RecurringTransaction_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `Category`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `RecurringTransaction_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
